[project]
name = "pbi-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "pandas>=3.0.0",
    "pythonnet>=3.0.5",
    "semantic-link>=0.13.0",
]
